version: "3"

services:
  angular:
    build: ./angular
    ports:
      - "8090:80"
  java:
    build: ./java
    ports:
      - "8080:8080"
  nodejs:
    build: ./nodejs
    ports:
      - "8081:8080"
  python:
    build: ./python
    ports:
      - "8082:8080"